#!/usr/bin/env bash

if test ! $# -eq 1; then
    echo "please specify the dir to work on"
fi

# TODO: png jpeg gif

for f in $(find $1 -type f | grep -v '\.gz$'); do
    if test "$f" -nt "${f}.gz"; then
        gzip -c "$f" > "${f}.gz"
        touch "${f}.gz" -r "$f"
    fi
done
